
services:
  b3:
    image: ghcr.io/groundsgg/b3:latest
    container_name: b3
    ports:
      - "8080:8080"

    environment:
      WEB_BASE_URL: "https://b3.example.com"
      WEB_SESSION_SIGN_KEY: aVerySecureKeyaVerySecureKey
      WEB_SESSION_ENCRYPT_KEY: aVerySecureKeyaVerySecureKey
      AUTH_TYPE: basic_auth
      # admin:admin (Admin) and visitor:visitor (Viewer)
      AUTH_BASIC_USERS: 'admin:20:$2a$10$F.9XEuzSgSimEHusYJdjBOSHD5VOqxW6apw5lVwEQaLRmer1sqiNe,visitor:5:$2a$10$rwLxV10P/iOwra5Z.wAGUeRO3SC91/XQCZxBbyLrx162v7A1JCega'

    restart: unless-stopped
